import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms & Conditions | MBBS Admissions in Abroad",
  description:
    "Read the Terms & Conditions for VST NEW-LYF PRARAMBHA PVT. LTD and the use of mbbsadmissionsinabroad.com.",
  alternates: {
    canonical: "https://www.mbbsadmissionsinabroad.com/terms-and-conditions",
  },
  robots: {
    index: true,
    follow: true,
  },
};

const sections = [
  {
    title: "General Terms",
    body: [
      "By accessing and placing an order with VST NEW-LYF PRARAMBHA PVT. LTD, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and VST NEW-LYF PRARAMBHA PVT. LTD.",
      "Under no circumstances shall the VST NEW-LYF PRARAMBHA PVT. LTD team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if VST NEW-LYF PRARAMBHA PVT. LTD or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.",
      "VST NEW-LYF PRARAMBHA PVT. LTD will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.",
    ],
  },
  {
    title: "License",
    body: [
      "VST NEW-LYF PRARAMBHA PVT. LTD grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement.",
      'These Terms & Conditions are a contract between you and VST NEW-LYF PRARAMBHA PVT. LTD (referred to in these Terms & Conditions as "VST NEW-LYF PRARAMBHA PVT. LTD", "us", "we" or "our"), the provider of the VST NEW-LYF PRARAMBHA PVT. LTD website (which are collectively referred to in these Terms & Conditions as the "Service").',
      'You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.',
    ],
  },
  {
    title: "Definitions and Key Terms",
    body: [
      "Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.",
      'Company: when this terms mention "Company," "we," "us," or "our," it refers to VST NEW-LYF PRARAMBHA PVT. LTD, that is responsible for your information under this Terms & Conditions.',
      "Country: where VST NEW-LYF PRARAMBHA PVT. LTD or the owners/founders of VST NEW-LYF PRARAMBHA PVT. LTD are based, in this case is India (404, 1st floor, 4th A Cross Rd, HRBR Layout 2nd Block, HRBR Layout, Kalyan Nagar, Bengaluru, Karnataka 560043).",
      "Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit VST NEW-LYF PRARAMBHA PVT. LTD and use the services.",
      "Service: refers to the service provided by VST NEW-LYF PRARAMBHA PVT. LTD as described in the relative terms (if available) and on this platform.",
      "Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",
      "Website: VST NEW-LYF PRARAMBHA PVT. LTD's site, which can be accessed via this URL: https://www.mbbsadmissionsinabroad.com/",
      "You: a person or entity that is registered with VST NEW-LYF PRARAMBHA PVT. LTD to use the Services.",
    ],
  },
  {
    title: "Restrictions",
    body: [
      "You agree not to, and you will not permit others to:",
      "License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the Service or make the platform available to any third party.",
      "Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the Service.",
      "Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of VST NEW-LYF PRARAMBHA PVT. LTD or its affiliates, partners, suppliers or the licensors of the Service.",
    ],
  },
  {
    title: "Payment",
    body: [
      'If you register to any of our recurring payment plans, you agree to pay all fees or charges to your account for the Service in accordance with the fees, charges and billing terms in effect at the time that each fee or charge is due and payable. Unless otherwise indicated in an order form, you must provide VST NEW-LYF PRARAMBHA PVT. LTD with a valid credit card (Visa, MasterCard, or any other issuer accepted by us) ("Payment Provider") as a condition to signing up for the Premium plan. Your Payment Provider agreement governs your use of the designated credit card account, and you must refer to that agreement and not these Terms to determine your rights and liabilities with respect to your Payment Provider.',
      "By providing VST NEW-LYF PRARAMBHA PVT. LTD with your credit card number and associated payment information, you agree that VST NEW-LYF PRARAMBHA PVT. LTD is authorized to verify information immediately, and subsequently invoice your account for all fees and charges due and payable to VST NEW-LYF PRARAMBHA PVT. LTD hereunder and that no additional notice or consent is required. You agree to immediately notify VST NEW-LYF PRARAMBHA PVT. LTD of any change in your billing address or the credit card used for payment hereunder.",
      "VST NEW-LYF PRARAMBHA PVT. LTD reserves the right at any time to change its prices and billing methods, either immediately upon posting on our Site or by e-mail delivery to your organization's administrator(s). Any attorney fees, court costs, or other costs incurred in collection of delinquent undisputed amounts shall be the responsibility of and paid for by you.",
      "No contract will exist between you and VST NEW-LYF PRARAMBHA PVT. LTD for the Service until VST NEW-LYF PRARAMBHA PVT. LTD accepts your order by a confirmatory e-mail, SMS/MMS message, or other appropriate means of communication.",
    ],
  },
  {
    title: "Third-Party Services",
    body: [
      'We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third-Party Services").',
      "You acknowledge and agree that VST NEW-LYF PRARAMBHA PVT. LTD shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. VST NEW-LYF PRARAMBHA PVT. LTD does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.",
      "Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.",
    ],
  },
  {
    title: "Updates to Our Service",
    body: [
      'VST NEW-LYF PRARAMBHA PVT. LTD may from time to time provide enhancements or improvements to the features/functionality of the Service, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates").',
      "Updates may modify or delete certain features and/or functionalities of the Service. You agree that VST NEW-LYF PRARAMBHA PVT. LTD has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the Service to you.",
      "You further agree that all Updates will be (i) deemed to constitute an integral part of the Service, and (ii) subject to the terms and conditions of this Agreement.",
    ],
  },
  {
    title: "Changes To Our Terms & Conditions",
    body: [
      "You acknowledge and agree that VST NEW-LYF PRARAMBHA PVT. LTD may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at VST NEW-LYF PRARAMBHA PVT. LTD's sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform VST NEW-LYF PRARAMBHA PVT. LTD when you stop using the Service. You acknowledge and agree that if VST NEW-LYF PRARAMBHA PVT. LTD disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.",
      "If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date.",
    ],
  },
  {
    title: "Modifications to Our Service",
    body: [
      "VST NEW-LYF PRARAMBHA PVT. LTD reserves the right to modify, suspend or discontinue, temporarily or permanently, the Service or any service to which it connects, with or without notice and without liability to you.",
    ],
  },
  {
    title: "Term and Termination",
    body: [
      "This Agreement shall remain in effect until terminated by you or VST NEW-LYF PRARAMBHA PVT. LTD.",
      "VST NEW-LYF PRARAMBHA PVT. LTD may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.",
      "This Agreement will terminate immediately, without prior notice from VST NEW-LYF PRARAMBHA PVT. LTD, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the Service and all copies thereof from your computer.",
      "Upon termination of this Agreement, you shall cease all use of the Service and delete all copies of the Service from your computer.",
      "Termination of this Agreement will not limit any of VST NEW-LYF PRARAMBHA PVT. LTD's rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.",
    ],
  },
  {
    title: "Copyright Infringement Notice",
    body: [
      "If you are a copyright owner or such owner's agent and believe any material on our Service constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.",
    ],
  },
  {
    title: "Indemnification",
    body: [
      "You agree to indemnify and hold VST NEW-LYF PRARAMBHA PVT. LTD and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the Service; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.",
    ],
  },
  {
    title: "No Warranties",
    body: [
      'The Service is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, VST NEW-LYF PRARAMBHA PVT. LTD, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice.',
      "Without limitation to the foregoing, VST NEW-LYF PRARAMBHA PVT. LTD provides no warranty or undertaking, and makes no representation of any kind that the Service will meet your requirements, achieve any intended results, be compatible or work with any other software, websites, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.",
      "Without limiting the foregoing, neither VST NEW-LYF PRARAMBHA PVT. LTD nor any third-party provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Service, or the information, content, and materials or products included thereon; (ii) that the Service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Service; or (iv) that the Service, its servers, the content, or e-mails sent from or on behalf of VST NEW-LYF PRARAMBHA PVT. LTD are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.",
      "Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.",
    ],
  },
  {
    title: "Limitation of Liability",
    body: [
      "Notwithstanding any damages that you might incur, the entire liability of VST NEW-LYF PRARAMBHA PVT. LTD and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the Service.",
      "To the maximum extent permitted by applicable law, in no event shall VST NEW-LYF PRARAMBHA PVT. LTD or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the Service, third-party software and/or third-party hardware used with the Service, or otherwise in connection with any provision of this Agreement), even if VST NEW-LYF PRARAMBHA PVT. LTD or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.",
      "Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.",
    ],
  },
];

export default function TermsAndConditionsPage() {
  return (
    <main className="bg-slate-50">
      <section className="border-b border-slate-200 bg-white">
        <div className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8">
          <p className="text-sm font-semibold uppercase tracking-[0.24em] text-blue-700">
            Terms & Conditions
          </p>
          <h1 className="mt-4 text-4xl font-bold tracking-tight text-slate-900 sm:text-5xl">
            VST NEW-LYF PRARAMBHA PVT. LTD
          </h1>
          <p className="mt-4 text-base leading-7 text-slate-600">
            Updated at: April 6, 2026
          </p>
          <p className="mt-6 max-w-3xl text-base leading-8 text-slate-600">
            These terms apply to{" "}
            <Link
              href="https://www.mbbsadmissionsinabroad.com/"
              className="font-semibold text-blue-700 underline underline-offset-4"
            >
              https://www.mbbsadmissionsinabroad.com/
            </Link>{" "}
            and related communications operated by VST NEW-LYF PRARAMBHA PVT.
            LTD.
          </p>
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-4 py-14 sm:px-6 lg:px-8">
        <div className="space-y-10 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-10">
          {sections.map((section) => (
            <section key={section.title} className="space-y-4">
              <h2 className="text-2xl font-semibold text-slate-900">
                {section.title}
              </h2>
              {section.body.map((paragraph, index) => (
                <p
                  key={`${section.title}-${index}`}
                  className="text-sm leading-7 text-slate-700 sm:text-base"
                >
                  {paragraph}
                </p>
              ))}
            </section>
          ))}

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-slate-900">
              Contact Us
            </h2>
            <p className="text-sm leading-7 text-slate-700 sm:text-base">
              Don&apos;t hesitate to contact us if you have any questions.
            </p>
            <p className="text-sm leading-7 text-slate-700 sm:text-base">
              Via Email: ceo@new-lyf.com
            </p>
            <p className="text-sm leading-7 text-slate-700 sm:text-base">
              Via this Link: https://www.mbbsadmissionsinabroad.com/contact
            </p>
          </section>
        </div>
      </section>
    </main>
  );
}
